# Generated by Django 4.1 on 2024-01-20 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0003_message_to_user_alter_message_by_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="to_user",
        ),
    ]
